name: tab_newz
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  go_router: ^12.1.0
  http: ^1.1.0
  intl: ^0.18.1
  mocktail: ^1.0.1
  shared_preferences: ^2.2.2
  stream_transform: ^2.1.0
  svg_flutter: ^0.0.1
  tab_news_api:
    path: packages/tab_news_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
          style: italic
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf
